//
//===========================================================================================
//
//	This file is automatically generated by SetBld (x86 Unicode).
//
//	(c) 2003 - 2024 Macallan - mailto:ian.macallan@gmail.com
//
//	Generated : 02/07/2024 11:01:18
//
//===========================================================================================
//
#pragma once

#ifndef AUTOMATICVERSIONHEADER_H
#define AUTOMATICVERSIONHEADER_H    1

#ifdef UNICODE
#define PROGRAM_MAIL    L"mailto:ian.macallan@gmail.com"
#define PROGRAM_HTTP    L"https://www.macallan.org/"
#define PROGRAM_DWNL    L"https://home.macallan.org:9443/"
#define PROGRAM_WIKI    L"https://www.macallan.org/"
#define PROGRAM_FORUM   L"https://www.macallan.org/"
#define PROGRAM_MMSFAQ  L"https://www.macallan.org/"
#define PROGRAM_RSS     L"index.php?title=Special:Recentchanges&feed=rss"
#define PROGRAM_NEWS    L"news://home.macallan.org/macallan.mail.solution"
#define PROGRAM_SITE    L"www.macallan.org"
#define PROGRAM_NAME    L"WOE5Extract"
#ifdef _WIN64
#define PROGRAM_NAME_P  L"WOE5Extract (x64 Unicode)"
#else
#define PROGRAM_NAME_P  L"WOE5Extract (x86 Unicode)"
#endif
#define PROGRAM_SECT    L"WOE5Extract"
#define PROGRAM_REGKEY  L"Macallan\\WOE5Extract"
#define PROGRAM_SOFTKEY L"SOFTWARE\\Macallan\\WOE5Extract"
#define PROGRAM_CHARS   L"Unicode"
#else
#define PROGRAM_MAIL    "mailto:ian.macallan@gmail.com"
#define PROGRAM_HTTP    "https://www.macallan.org/"
#define PROGRAM_DWNL    "https://home.macallan.org:9443/"
#define PROGRAM_WIKI    "https://www.macallan.org/"
#define PROGRAM_FORUM   "https://www.macallan.org/"
#define PROGRAM_MMSFAQ  "https://www.macallan.org/"
#define PROGRAM_RSS     "index.php?title=Special:Recentchanges&feed=rss"
#define PROGRAM_NEWS    "news://home.macallan.org/macallan.mail.solution"
#define PROGRAM_SITE    "www.macallan.org"
#define PROGRAM_NAME    "WOE5Extract"
#ifdef _WIN64
#define PROGRAM_NAME_P  "WOE5Extract (x64 MBCS)"
#else
#define PROGRAM_NAME_P  "WOE5Extract (x86 MBCS)"
#endif
#define PROGRAM_SECT    "WOE5Extract"
#define PROGRAM_REGKEY  "Macallan\\WOE5Extract"
#define PROGRAM_SOFTKEY "SOFTWARE\\Macallan\\WOE5Extract"
#define PROGRAM_CHARS   "MBCS"
#endif

#ifdef UNICODE
#define PROGRAM_DATE    L"Tue Jul 02 11:01"
#define PROGRAM_DATE_F  L"Tue Jul 02 11:01 2024"
#define PROGRAM_YEAR    L"2024"
#define PROGRAM_TIME    L"2024/07/02 11:01:18"
#else
#define PROGRAM_DATE    "Tue Jul 02 11:01"
#define PROGRAM_DATE_F  "Tue Jul 02 11:01 2024"
#define PROGRAM_YEAR    "2024"
#define PROGRAM_TIME    "2024/07/02 11:01:18"
#endif

#ifdef UNICODE
#define PROGRAM_VERSION L"1.3.01.003"
#define PROGRAM_INSTALL L"1.3.01003"
#define PROGRAM_VER_NUM 10301003
#define PROGRAM_BUILD   L"164"
#define PROGRAM_TITLE   L"WOE5Extract"
#ifdef _WIN64
#define PROGRAM_TITLE_P L"WOE5Extract (x64 Unicode)"
#else
#define PROGRAM_TITLE_P L"WOE5Extract (x86 Unicode)"
#endif
#else
#define PROGRAM_VERSION "1.3.01.003"
#define PROGRAM_INSTALL "1.3.01003"
#define PROGRAM_VER_NUM 10301003
#define PROGRAM_BUILD   "164"
#define PROGRAM_TITLE   "WOE5Extract"
#ifdef _WIN64
#define PROGRAM_TITLE_P "WOE5Extract (x64 MBCS)"
#else
#define PROGRAM_TITLE_P "WOE5Extract (x86 MBCS)"
#endif
#endif

#endif

